### ISSUE TITLE
#5 Issues with Instruction Section HTML and CSS

### ISSUE THREAD

**Issue by syntaxSangoma** [AbigirlMuchineripi/Recipe-Page#5]
There are several problems identified in the HTML and CSS code for the instructions section of the recipe. Addressing these issues will enhance the functionality and appearance of the instruction list.

## Issues Found

1. #### Incorrect Class Usage in HTML:
- The ordered list (<ol>) is missing the instructions__ol class, which is defined in the CSS. This class is crucial for the custom styling of the list items.
- Fix: Update the <ol> tag to include the class
```
<ol class="instructions__ol">

```

2. #### Typographical Error in Instruction Text:
- The text "Add fillings (optiona)" contains a typographical error ("optiona" should be "optional").
- Fix: Correct the text in the fourth instruction item.

3. #### CSS Selector Specificity:
- The CSS rules for .instructions__ol li and the pseudo-element ::before rely on the .instructions__ol class, which will not apply until the class is added to the HTML.

## Suggested Fixes
Updated HTML:
```
<section class="text-content__instructions">
    <h2 class="instructions__title">Instructions</h2>
    <ol class="instructions__ol">
        <li>
            <p>
                <span class="bold">Beat the eggs</span>: In a bowl, beat the
                eggs with a pinch of salt and pepper until they are well mixed.
                You can add a tablespoon of water or milk for a fluffier
                texture.
            </p>
        </li>
        <li>
            <p>
                <span class="bold">Heat the pan</span>: Place a non-stick frying
                pan over medium heat and add butter or oil.
            </p>
        </li>
        <li>
            <p>
                <span class="bold">Cook the omelette</span>: Once the butter is
                melted and bubbling, pour in the eggs. Tilt the pan to ensure
                the eggs evenly coat the surface.
            </p>
        </li>
        <li>
            <p>
                <span class="bold">Add fillings (optional)</span>: When the eggs
                begin to set at the edges but are still slightly runny in the
                middle, sprinkle your chosen fillings over one half of the
                omelette. 
            </p>
        </li>
        <li>
            <p>
                <span class="bold">Fold and serve</span>: As the omelette
                continues to cook, carefully lift one edge and fold it over the
                fillings. Let it cook for another minute, then slide it onto a
                plate.
            </p>
        </li>
        <li>
            <p>
                <span class="bold">Enjoy</span>: Serve hot, with additional salt
                and pepper if needed.
            </p>
        </li>
    </ol>
</section>
```

## Expected Outcome
By implementing these changes, the instruction section will have consistent styling, improved readability, and accurate text, contributing to a better user experience.

**Comment by AbigirlMuchineripi** [comment]
Thank you, on this one I am failing to see the CSS selector specificity issue in the HTML code would you kindly explain more.

**Comment by syntaxSangoma** [comment]
> Thank you, on this one I am failing to see the CSS selector specificity issue in the HTML code would you kindly explain more.

Initially, the class wasn't declared in the HTML. The CSS rules for `.instructions__ol li` and the `::before` pseudo-element depend on the `.instructions__ol` class, which won't take effect until that class is added to the HTML. You fixed it by declaring the `.instructions__ol` class.
